# Generated by Django 4.2.30 on 2026-05-13 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_company_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Número')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('respondida', 'Respondida'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('notas_buyer', models.TextField(blank=True, verbose_name='Notas del comprador')),
                ('notas_seller', models.TextField(blank=True, verbose_name='Notas del vendedor')),
                ('validez_dias', models.PositiveIntegerField(default=30, verbose_name='Validez (días)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to=settings.AUTH_USER_MODEL, verbose_name='Comprador')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='core.company', verbose_name='Empresa')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizacion_origen', to='core.order', verbose_name='Orden generada')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.PositiveIntegerField(verbose_name='Cantidad solicitada')),
                ('precio_ofertado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio ofertado (unitario)')),
                ('notas', models.TextField(blank=True, verbose_name='Notas de línea')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.cotizacion', verbose_name='Cotización')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Ítem de cotización',
                'verbose_name_plural': 'Ítems de cotización',
            },
        ),
    ]
