# Generated by Django 4.2

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0004_cotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='latitud',
            field=models.FloatField(
                blank=True,
                default=9.3667,
                null=True,
                verbose_name='Latitud (ZLC)',
            ),
        ),
        migrations.AddField(
            model_name='company',
            name='longitud',
            field=models.FloatField(
                blank=True,
                default=-79.9000,
                null=True,
                verbose_name='Longitud (ZLC)',
            ),
        ),
    ]
