# Generated by Django 4.2.30 on 2026-05-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile_email_verification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-merchandising_priority', 'name'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='company',
            name='carousel_priority',
            field=models.IntegerField(default=0, verbose_name='Prioridad carrusel'),
        ),
        migrations.AddField(
            model_name='company',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Destacada en home'),
        ),
        migrations.AddField(
            model_name='company',
            name='tagline_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Eslogan (EN)'),
        ),
        migrations.AddField(
            model_name='company',
            name='tagline_es',
            field=models.CharField(blank=True, max_length=200, verbose_name='Eslogan (ES)'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_bestseller',
            field=models.BooleanField(default=False, verbose_name='Más vendido (manual o recalculado)'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Destacado'),
        ),
        migrations.AddField(
            model_name='product',
            name='merchandising_priority',
            field=models.IntegerField(default=0, verbose_name='Prioridad merchandising'),
        ),
        migrations.AddField(
            model_name='product',
            name='promo_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='promo_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio promocional'),
        ),
        migrations.AddField(
            model_name='product',
            name='promo_starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HomePromoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('section_type', models.CharField(choices=[('product_row', 'Fila de productos'), ('product_carousel', 'Carrusel de productos'), ('category_spotlight', 'Destacado por categoría'), ('company_spotlight', 'Destacado por empresa'), ('seasonal_banner', 'Banner de temporada'), ('bestsellers', 'Más vendidos'), ('daily_deals', 'Ofertas del día')], max_length=32)),
                ('title_es', models.CharField(max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('subtitle_es', models.CharField(blank=True, max_length=300)),
                ('subtitle_en', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('max_items', models.PositiveSmallIntegerField(default=8)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='promo_sections', to='core.category', verbose_name='Categorías')),
                ('companies', models.ManyToManyField(blank=True, related_name='promo_sections', to='core.company', verbose_name='Empresas')),
                ('products', models.ManyToManyField(blank=True, related_name='promo_sections', to='core.product', verbose_name='Productos')),
            ],
            options={
                'verbose_name': 'Sección promocional home',
                'verbose_name_plural': 'Secciones promocionales home',
                'ordering': ['sort_order', 'slug'],
            },
        ),
    ]
