# Generated by Django 4.2.30 on 2026-05-23 02:24

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_transport_carrier_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaasPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('monthly_volume_limit_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Null = volumen ilimitado', max_digits=14, null=True)),
                ('ad_credits_monthly', models.PositiveIntegerField(default=0)),
                ('api_access', models.BooleanField(default=False)),
                ('logistics_webhooks', models.BooleanField(default=False)),
                ('priority_support', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plan SaaS',
                'verbose_name_plural': 'Planes SaaS',
                'ordering': ['sort_order', 'slug'],
            },
        ),
        migrations.AddField(
            model_name='shipment',
            name='dimensions_cm',
            field=models.CharField(blank=True, max_length=80, verbose_name='Dimensiones L×A×H (cm)'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pickup_lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pickup_lng',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='route_code',
            field=models.CharField(blank=True, max_length=40, verbose_name='Ruta'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='warehouse_code',
            field=models.CharField(blank=True, max_length=40, verbose_name='Bodega ZLC'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Peso (kg)'),
        ),
        migrations.CreateModel(
            name='LogisticsWebhookConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Aliado logístico', max_length=120)),
                ('endpoint_url', models.URLField(max_length=500)),
                ('signing_secret', models.CharField(max_length=128)),
                ('events', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logistics_webhooks', to='core.company')),
            ],
            options={
                'verbose_name': 'Webhook logístico',
                'verbose_name_plural': 'Webhooks logísticos',
            },
        ),
        migrations.CreateModel(
            name='LogisticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=40)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(default='system', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_events', to='core.order')),
            ],
            options={
                'verbose_name': 'Evento logístico',
                'verbose_name_plural': 'Eventos logísticos',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogisticsDispatchQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='pending', max_length=12)),
                ('payload', models.JSONField(default=dict)),
                ('signature', models.CharField(blank=True, max_length=128)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_dispatches', to='core.company')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_dispatches', to='core.order')),
            ],
            options={
                'verbose_name': 'Cola despacho logístico',
                'verbose_name_plural': 'Cola despacho logístico',
            },
        ),
        migrations.CreateModel(
            name='CompanySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trialing', 'Prueba'), ('active', 'Activa'), ('past_due', 'Pago pendiente'), ('cancelled', 'Cancelada')], default='active', max_length=12)),
                ('current_period_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_period_end', models.DateTimeField()),
                ('auto_renew', models.BooleanField(default=True)),
                ('upgraded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='core.company')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='core.saasplan')),
            ],
            options={
                'verbose_name': 'Suscripción empresa',
                'verbose_name_plural': 'Suscripciones empresa',
            },
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('key_prefix', models.CharField(editable=False, max_length=12)),
                ('key_hash', models.CharField(editable=False, max_length=64)),
                ('scopes', models.JSONField(default=list, help_text='inventory.read, pricing.write, webhooks.receive')),
                ('is_active', models.BooleanField(default=True)),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
            },
        ),
        migrations.CreateModel(
            name='ApiAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=255)),
                ('status_code', models.PositiveSmallIntegerField(default=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.apikey')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_audit_logs', to='core.company')),
            ],
            options={
                'verbose_name': 'Auditoría API',
                'verbose_name_plural': 'Auditoría API',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdCreditAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0)),
                ('lifetime_spent', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ad_credits', to='core.company')),
            ],
            options={
                'verbose_name': 'Cuenta créditos ads',
                'verbose_name_plural': 'Cuentas créditos ads',
            },
        ),
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('placement', models.CharField(choices=[('search', 'Búsqueda'), ('home', 'Home'), ('category', 'Categoría')], default='search', max_length=20)),
                ('boost_weight', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=5)),
                ('credits_budget', models.PositiveIntegerField(default=0)),
                ('credits_spent', models.PositiveIntegerField(default=0)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_campaigns', to='core.company')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_campaigns', to='core.product')),
            ],
            options={
                'verbose_name': 'Campaña publicitaria',
                'verbose_name_plural': 'Campañas publicitarias',
            },
        ),
        migrations.CreateModel(
            name='CompanyBillingUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.PositiveSmallIntegerField()),
                ('period_month', models.PositiveSmallIntegerField()),
                ('volume_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('orders_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_usage', to='core.company')),
            ],
            options={
                'verbose_name': 'Uso facturación mensual',
                'verbose_name_plural': 'Uso facturación mensual',
                'unique_together': {('company', 'period_year', 'period_month')},
            },
        ),
    ]
