# Generated by Django 4.2.30 on 2026-05-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_email_delivery_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapplication',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=12),
        ),
    ]
