# Generated by Django 4.2.30 on 2026-05-23 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_userapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='saasplan',
            name='predictive_ai',
            field=models.BooleanField(default=False, verbose_name='IA predictiva Enterprise'),
        ),
        migrations.CreateModel(
            name='CompanyPredictiveSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_key', models.CharField(db_index=True, max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictive_snapshots', to='core.company')),
            ],
            options={
                'verbose_name': 'Snapshot predictivo',
                'verbose_name_plural': 'Snapshots predictivos',
                'ordering': ['-computed_at'],
                'unique_together': {('company', 'period_key')},
            },
        ),
    ]
