# Generated by Django 4.2.30 on 2026-05-25 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_saas_commercial_upgrade_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionupgradelog',
            name='source',
            field=models.CharField(choices=[('self_serve', 'Activación seller'), ('checkout', 'Pago checkout'), ('commercial', 'Aprobación comercial'), ('admin', 'Administrador')], default='self_serve', max_length=20),
        ),
        migrations.CreateModel(
            name='CompanyPlanCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('billing_label', models.CharField(default='Mensual', max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pendiente de pago'), ('paid', 'Pagado'), ('cancelled', 'Cancelado'), ('expired', 'Expirado')], default='pending', max_length=12)),
                ('provider', models.CharField(choices=[('mock', 'Tarjeta (demo)'), ('stripe', 'Stripe'), ('bank', 'Transferencia')], default='mock', max_length=12)),
                ('txn_ref', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_checkouts', to='core.company')),
                ('from_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkouts_from', to='core.saasplan')),
                ('target_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkouts_to', to='core.saasplan')),
            ],
            options={
                'verbose_name': 'Checkout plan SaaS',
                'verbose_name_plural': 'Checkouts plan SaaS',
                'ordering': ['-created_at'],
            },
        ),
    ]
