# Generated by Django 6.0.5 on 2026-05-29 21:50

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_email_verification_resend'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Direcciones'},
        ),
        migrations.AlterModelOptions(
            name='emailverification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Email verification', 'verbose_name_plural': 'Email verifications'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User profile', 'verbose_name_plural': 'User profiles'},
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='Panamá', max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='line1',
            field=models.CharField(max_length=255, verbose_name='Address line 1'),
        ),
        migrations.AlterField(
            model_name='address',
            name='line2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address line 2'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='asignaciontransporte',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente confirmación'), ('confirmado', 'Transportista confirmó'), ('en_camino', 'En camino'), ('entregado', 'Delivered'), ('cancelado', 'Cancelled')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_text',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Featured on home'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Verified?'),
        ),
        migrations.AlterField(
            model_name='company',
            name='latitud',
            field=models.FloatField(blank=True, default=9.3667, null=True, verbose_name='Latitude (CFZ)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='longitud',
            field=models.FloatField(blank=True, default=-79.9, null=True, verbose_name='Longitude (CFZ)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_companies', to=settings.AUTH_USER_MODEL, verbose_name='Owner (seller)'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pending'), ('respondida', 'Respondida'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='numero',
            field=models.CharField(editable=False, max_length=30, unique=True, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='validez_dias',
            field=models.PositiveIntegerField(default=30, verbose_name='Validity (days)'),
        ),
        migrations.AlterField(
            model_name='cotizacionitem',
            name='cotizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.cotizacion', verbose_name='Quote'),
        ),
        migrations.AlterField(
            model_name='cotizacionitem',
            name='notas',
            field=models.TextField(blank=True, verbose_name='Line notes'),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Document number'),
        ),
        migrations.AlterField(
            model_name='homepromosection',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='promo_sections', to='core.category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='homepromosection',
            name='section_type',
            field=models.CharField(choices=[('product_row', 'View products'), ('product_carousel', 'View products'), ('category_spotlight', 'By category'), ('company_spotlight', 'By company'), ('seasonal_banner', 'Banner de temporada'), ('bestsellers', 'Bestsellers'), ('daily_deals', 'Daily deals')], max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer_location_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Confirmed location'),
        ),
        migrations.AlterField(
            model_name='order',
            name='confirmado_por_empresa',
            field=models.BooleanField(blank=True, help_text='True=aceptado, False=rechazado, None=pendiente', null=True, verbose_name='Company confirmation'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(editable=False, max_length=30, unique=True, verbose_name='Order number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('b2c', 'End consumer (B2C)'), ('b2b', 'Business to business (B2B)')], default='b2c', max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='seller_confirmation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada'), ('expired', 'Expirada')], default='pending', max_length=12, verbose_name='Seller confirmation'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ship_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.address', verbose_name='Shipping address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('awaiting_seller', 'Esperando confirmación'), ('pending', 'Pending'), ('paid', 'Paid'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='tiempo_confirmacion_horas',
            field=models.PositiveIntegerField(default=24, verbose_name='Hours for company confirmation'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('refunded', 'Reembolsado')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='txn_ref',
            field=models.CharField(blank=True, max_length=200, verbose_name='Transaction reference'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_bestseller',
            field=models.BooleanField(default=False, verbose_name='Bestseller (manual or recalculated)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Product name'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='courier_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Courier'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ship date'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('label', 'Etiqueta generada'), ('in_transit', 'En tránsito'), ('delivered', 'Delivered'), ('returned', 'Devuelto')], default='label', max_length=12),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tracking number'),
        ),
        migrations.AlterField(
            model_name='transportcarrier',
            name='base_shipping_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Base shipping cost (USD)'),
        ),
        migrations.AlterField(
            model_name='transportcarrier',
            name='code',
            field=models.SlugField(max_length=40, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='transportcarrier',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='cobertura_descripcion',
            field=models.TextField(help_text='Cityes o zonas que cubre'),
        ),
        migrations.AlterField(
            model_name='userapplication',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='userapplication',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller')], default='buyer', max_length=10),
        ),
        migrations.AlterField(
            model_name='userapplication',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pending'), ('en_revision', 'En revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=12),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='codigo_verificacion_email',
            field=models.CharField(blank=True, max_length=6, verbose_name='Email verification code'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='codigo_verificacion_expira',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Email code expiration'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_verificado',
            field=models.BooleanField(default=False, verbose_name='Email verified'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('buyer', 'Comprador'), ('seller', 'Vendedor'), ('admin', 'Administrador'), ('transportista', 'Transportista')], default='buyer', max_length=14, verbose_name='Role'),
        ),
    ]
