# Generated by Django 6.0.5 on 2026-05-30 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_address_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='asignaciontransporte',
            options={'verbose_name': 'Transport assignment', 'verbose_name_plural': 'Transport assignments'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Quote', 'verbose_name_plural': 'Quotes'},
        ),
        migrations.AlterModelOptions(
            name='cotizacionitem',
            options={'verbose_name': 'Quote item', 'verbose_name_plural': 'Quote items'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='homepromosection',
            options={'ordering': ['sort_order', 'slug'], 'verbose_name': 'Home promotional section', 'verbose_name_plural': 'Home promotional sections'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'Inventory', 'verbose_name_plural': 'Inventories'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Order item', 'verbose_name_plural': 'Order items'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-merchandising_priority', 'name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='shipment',
            options={'verbose_name': 'Shipment', 'verbose_name_plural': 'Shipments'},
        ),
        migrations.AlterModelOptions(
            name='transportcarrier',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Transport carrier', 'verbose_name_plural': 'Transport carriers'},
        ),
        migrations.AlterModelOptions(
            name='transportista',
            options={'verbose_name': 'Carrier', 'verbose_name_plural': 'Carriers'},
        ),
        migrations.AlterModelOptions(
            name='userapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'Access request', 'verbose_name_plural': 'Access requests'},
        ),
        migrations.AlterField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Default?'),
        ),
        migrations.AlterField(
            model_name='address',
            name='label',
            field=models.CharField(blank=True, max_length=100, verbose_name='Label (e.g. Home, Office)'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='asignaciontransporte',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pending confirmation'), ('confirmado', 'Carrier confirmed'), ('en_camino', 'On the way'), ('entregado', 'Delivered'), ('cancelado', 'Cancelled')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='carousel_priority',
            field=models.IntegerField(default=0, verbose_name='Carousel priority'),
        ),
        migrations.AlterField(
            model_name='company',
            name='order_confirm_hours',
            field=models.PositiveIntegerField(default=48, help_text='Deadline for the company to accept or reject a new order.', verbose_name='Hours to confirm order'),
        ),
        migrations.AlterField(
            model_name='company',
            name='ruc',
            field=models.CharField(blank=True, max_length=50, verbose_name='RUC / Registration'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tagline_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tagline (EN)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tagline_es',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tagline (ES)'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to=settings.AUTH_USER_MODEL, verbose_name='Buyer'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='core.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pending'), ('respondida', 'Responded'), ('aceptada', 'Accepted'), ('rechazada', 'Rejected')], default='pendiente', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='notas_buyer',
            field=models.TextField(blank=True, verbose_name='Buyer notes'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='notas_seller',
            field=models.TextField(blank=True, verbose_name='Seller notes'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizacion_origen', to='core.order', verbose_name='Generated order'),
        ),
        migrations.AlterField(
            model_name='cotizacionitem',
            name='cantidad_solicitada',
            field=models.PositiveIntegerField(verbose_name='Requested quantity'),
        ),
        migrations.AlterField(
            model_name='cotizacionitem',
            name='precio_ofertado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Offered price (unit)'),
        ),
        migrations.AlterField(
            model_name='cotizacionitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('packing_list', 'Packing List'), ('other', 'Other')], default='invoice', max_length=15),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='document',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='homepromosection',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='promo_sections', to='core.company', verbose_name='Companies'),
        ),
        migrations.AlterField(
            model_name='homepromosection',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='promo_sections', to='core.product', verbose_name='Products'),
        ),
        migrations.AlterField(
            model_name='homepromosection',
            name='section_type',
            field=models.CharField(choices=[('product_row', 'View products'), ('product_carousel', 'View products'), ('category_spotlight', 'By category'), ('company_spotlight', 'By company'), ('seasonal_banner', 'Seasonal banner'), ('bestsellers', 'Bestsellers'), ('daily_deals', 'Daily deals')], max_length=32),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='low_stock_alert',
            field=models.PositiveIntegerField(default=5, verbose_name='Low stock alert'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='core.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='reserved_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='Reserved quantity'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Buyer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Buyer latitude'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Buyer longitude'),
        ),
        migrations.AlterField(
            model_name='order',
            name='confirmado_por_empresa',
            field=models.BooleanField(blank=True, help_text='True=accepted, False=rejected, None=pending', null=True, verbose_name='Company confirmation'),
        ),
        migrations.AlterField(
            model_name='order',
            name='confirming_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_to_confirm', to='core.company', verbose_name='Confirming company'),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='order',
            name='seller_confirm_by',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Confirm by'),
        ),
        migrations.AlterField(
            model_name='order',
            name='seller_confirmation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=12, verbose_name='Seller confirmation'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('awaiting_seller', 'Awaiting confirmation'), ('pending', 'Pending'), ('paid', 'Paid'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='transport_carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.transportcarrier', verbose_name='Transport carrier'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='qty',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price_snapshot',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Unit price (at time of sale)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='core.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('mock', 'Mock (development)'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('bank', 'Bank transfer')], default='mock', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('refunded', 'Refunded')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar (USD)'), ('PAB', 'Panamanian Balboa (PAB)')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Featured'),
        ),
        migrations.AlterField(
            model_name='product',
            name='merchandising_priority',
            field=models.IntegerField(default=0, verbose_name='Merchandising priority'),
        ),
        migrations.AlterField(
            model_name='product',
            name='promo_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Promotional price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Unit price'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Delivery date'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='dimensions_cm',
            field=models.CharField(blank=True, max_length=80, verbose_name='Dimensions L×W×H (cm)'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='core.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='route_code',
            field=models.CharField(blank=True, max_length=40, verbose_name='Route'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('label', 'Label generated'), ('in_transit', 'In transit'), ('delivered', 'Delivered'), ('returned', 'Returned')], default='label', max_length=12),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Weight (kg)'),
        ),
        migrations.AlterField(
            model_name='transportcarrier',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='transportcarrier',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='transportcarrier',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sort order'),
        ),
        migrations.AlterField(
            model_name='transportcarrier',
            name='transport_mode',
            field=models.CharField(choices=[('maritime', 'Maritime'), ('air', 'Air'), ('terrestrial', 'Terrestrial'), ('mixed', 'Mixed')], default='terrestrial', max_length=12, verbose_name='Transport mode'),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='cobertura_descripcion',
            field=models.TextField(help_text='Cities or areas covered'),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pending review'), ('aprobado', 'Approved'), ('rechazado', 'Rejected')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='userapplication',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='userapplication',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='userapplication',
            name='full_name',
            field=models.CharField(max_length=120, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='userapplication',
            name='message',
            field=models.TextField(blank=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='userapplication',
            name='requested_plan_slug',
            field=models.CharField(blank=True, help_text='Requested SaaS plan (e.g. ecosistema_enterprise)', max_length=40),
        ),
        migrations.AlterField(
            model_name='userapplication',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pending'), ('en_revision', 'Under review'), ('aprobada', 'Approved'), ('rechazada', 'Rejected')], default='pendiente', max_length=12),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('admin', 'Administrator'), ('transportista', 'Carrier')], default='buyer', max_length=14, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='token_verificacion',
            field=models.CharField(blank=True, help_text='UUID token for email verification', max_length=64, null=True),
        ),
    ]
