# Generated by Django 6.0.5 on 2026-05-30 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_english_model_labels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adcampaign',
            options={'verbose_name': 'Ad campaign', 'verbose_name_plural': 'Ad campaigns'},
        ),
        migrations.AlterModelOptions(
            name='adcreditaccount',
            options={'verbose_name': 'Ad credits account', 'verbose_name_plural': 'Ad credits accounts'},
        ),
        migrations.AlterModelOptions(
            name='apiauditlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'API audit log', 'verbose_name_plural': 'API audit logs'},
        ),
        migrations.AlterModelOptions(
            name='companybillingusage',
            options={'verbose_name': 'Monthly billing usage', 'verbose_name_plural': 'Monthly billing usage'},
        ),
        migrations.AlterModelOptions(
            name='companyplancheckout',
            options={'ordering': ['-created_at'], 'verbose_name': 'SaaS plan checkout', 'verbose_name_plural': 'SaaS plan checkouts'},
        ),
        migrations.AlterModelOptions(
            name='companyplancommercialrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Commercial plan request', 'verbose_name_plural': 'Commercial plan requests'},
        ),
        migrations.AlterModelOptions(
            name='companypredictivesnapshot',
            options={'ordering': ['-computed_at'], 'verbose_name': 'Predictive snapshot', 'verbose_name_plural': 'Predictive snapshots'},
        ),
        migrations.AlterModelOptions(
            name='companysubscription',
            options={'verbose_name': 'Company subscription', 'verbose_name_plural': 'Company subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='emaildeliverylog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Email log', 'verbose_name_plural': 'Email logs'},
        ),
        migrations.AlterModelOptions(
            name='logisticsdispatchqueue',
            options={'verbose_name': 'Logistics dispatch queue', 'verbose_name_plural': 'Logistics dispatch queue'},
        ),
        migrations.AlterModelOptions(
            name='logisticsevent',
            options={'ordering': ['created_at'], 'verbose_name': 'Logistics event', 'verbose_name_plural': 'Logistics events'},
        ),
        migrations.AlterModelOptions(
            name='logisticswebhookconfig',
            options={'verbose_name': 'Logistics webhook', 'verbose_name_plural': 'Logistics webhooks'},
        ),
        migrations.AlterModelOptions(
            name='saasplan',
            options={'ordering': ['sort_order', 'slug'], 'verbose_name': 'SaaS plan', 'verbose_name_plural': 'SaaS plans'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionupgradelog',
            options={'ordering': ['-activated_at'], 'verbose_name': 'Plan upgrade history', 'verbose_name_plural': 'Plan upgrade history'},
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='placement',
            field=models.CharField(choices=[('search', 'Search'), ('home', 'Home'), ('category', 'Category')], default='search', max_length=20),
        ),
        migrations.AlterField(
            model_name='companyplancheckout',
            name='billing_label',
            field=models.CharField(default='Monthly', max_length=40),
        ),
        migrations.AlterField(
            model_name='companyplancheckout',
            name='provider',
            field=models.CharField(choices=[('mock', 'Card (demo)'), ('stripe', 'Stripe'), ('bank', 'Bank transfer')], default='mock', max_length=12),
        ),
        migrations.AlterField(
            model_name='companyplancheckout',
            name='status',
            field=models.CharField(choices=[('pending', 'Payment pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='companyplancommercialrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('en_revision', 'Under review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='companysubscription',
            name='status',
            field=models.CharField(choices=[('trialing', 'Trial'), ('active', 'Active'), ('past_due', 'Payment past due'), ('cancelled', 'Cancelled')], default='active', max_length=12),
        ),
        migrations.AlterField(
            model_name='emaildeliverylog',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('queued', 'Queued')], default='queued', max_length=12),
        ),
        migrations.AlterField(
            model_name='logisticsdispatchqueue',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='logisticswebhookconfig',
            name='name',
            field=models.CharField(default='Logistics partner', max_length=120),
        ),
        migrations.AlterField(
            model_name='saasplan',
            name='monthly_volume_limit_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Null = unlimited volume', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='saasplan',
            name='predictive_ai',
            field=models.BooleanField(default=False, verbose_name='Enterprise predictive AI'),
        ),
        migrations.AlterField(
            model_name='subscriptionupgradelog',
            name='source',
            field=models.CharField(choices=[('self_serve', 'Seller activation'), ('checkout', 'Checkout payment'), ('commercial', 'Commercial approval'), ('admin', 'Administrator')], default='self_serve', max_length=20),
        ),
    ]
