# Generated by Django 4.2.30 on 2026-06-04 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_userapplication_english_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='es_automatica',
            field=models.BooleanField(default=False, help_text='Generated automatically with catalog pricing (no manual seller reply).', verbose_name='Automatic quote'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='lote',
            field=models.CharField(blank=True, db_index=True, help_text='Groups quotes created together from one automatic request.', max_length=40, verbose_name='Broadcast batch'),
        ),
    ]
