# Generated by Django 6.0.5 on 2026-07-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cart_items_count',
            field=models.PositiveIntegerField(default=0, help_text='Units in session cart — used for abandonment reminders.', verbose_name='Cart items (snapshot)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cart_last_activity_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last cart activity'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cart_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last cart reminder sent'),
        ),
    ]
