# Generated by Django 6.0.5 on 2026-07-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_userprofile_onboarding_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=100, verbose_name='Product code'),
        ),
    ]
